fringd/zipline

lib/zipline/output_stream.rb
The ZIP spec [1] describes in section 4.4.9 that the uncompressed size
field is set to zero in the local file header if bit 3 of the general
purpose flags is set, which zipline does.
Some applications actually care about this, e.g. Powerpoint regards a
file as corrupt when the uncompressed size and bit 3 are set.
[1] https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
=> Set uncompressed size in local file header to 0

lib/zipline.rb
To allow to use space in zip filename it should be quoted as described in [RFC2616, 19.5.1 Content-Disposition](http://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html). Otherwise the filename will be truncated. e.g. "ab cd.zip" => "ab".
=> Use zip filename in Content-Disposition as quoted string.

README.md
Give example of using open-uri with lazy enumerators to begin streaming
download immediately instead of waiting for all files to download from
the remote server.
=> Add documentation for streaming from remote URLs.

lib/zipline/zip_generator.rb, zipline.gemspec
Hi @fringd 
We created functionality of filename cleaning (backslashes removing) and uniquely filenames in `zip_tricks`: https://github.com/WeTransfer/zip_tricks/pull/6
It adds `(n)` at the end of filename for duplicated names instead of `_n`.
I hope it's ok for you :)
=> Remove uniquify for filenames

lib/zipline/zip_generator.rb, spec/lib/zipline/zip_generator_spec.rb
It supports instance of CarrierWave uploader that inherits from `CarrierWave::Uploader::Base`. When using CarrierWave, mount the uploader as follows.
```rb
class AvatarUploader < CarrierWave::Uploader::Base
storage :file
end
class User < ActiveRecord::Base
mount_uploader :avatar, AvatarUploader
end
```
If you want to distribute the mounted file, you can do as follows.
```rb
def index
users = User.all
files =  users.map{ |user| [user.avatar, "#{user.username}.png"] }
zipline( files, 'avatars.zip')
end
```
Fix #28
=> Support CarrierWave::Uploader

lib/zipline.rb
I believe it's better to use `Time.now.httpdate` (returns a string which represents the time as RFC 1123 date of HTTP-date defined by RFC 2616) instead of `Time.now.to_s`.
This helps to avoid situations like this `ArgumentError: not RFC 2616 compliant date: "2017-08-25 13:26:14 +0000"`
=> Use Time.now.httpdate instead of Time.now.to_s

lib/zipline/zip_generator.rb
It was leaking open files before. I tested using Shrine and [this code](https://stackoverflow.com/a/10922046/1928168) where I saw a lot of open files before this change.
Also, I messed up with my branching, so #34 is included in this PR as well ._.
I suggest to either accept just this PR (if there's no objections) or I can rebase this one after #34 is merged.
=> Close file descriptor after writing.

lib/zipline/zip_generator.rb, spec/lib/zipline/zip_generator_spec.rb
Add support for ActiveStorage::Blobs.
The tests aren't the best, `require 'active_storage'` directly without passing through all the Railties stuff doesn't import `ActiveStorage::Blob`, so I had to get creative with the tests, I'm open for suggestions.
=> Add support for ActiveStorage::Blobs

zipline.gemspec
This allows the gem to be used with Rails 6.0.0.beta-1 for example.
Part of #42.
=> Allow Rails 6 preview versions

README.md
If the options hash isn't mapped, modification times won't be reflected in the resulting zip.
=> Update README for streaming example with modification times

lib/zipline.rb, lib/zipline/zip_generator.rb, zipline.gemspec
Fixes #51.
You can check out https://github.com/aried3r/zipline-rails-6-poc/tree/ar/replace_curb. ~The commit previous to HEAD uses zipline master, the current HEAD uses my patched version (see this PR).~ The commit previous to HEAD does not work, because it doesn't contain the patch applied in this PR which checks if a string is probably a URL.
~In my local tests, neither curb nor Net::HTTP directly stream the download from the wire but only begin streaming once the download completes. I also tried playing around with `IO.copy_stream`, but I'm not  exactly sure what's going on.~
Chunks from the wire are directly streamed to the writer.
~However, both versions exhibit the exact same behavior.~ I didn't test the curb version with the current form of this PR.
Here's a ~100MB video, if you …
=> Replace curb with Net::HTTP

zipline.gemspec
Is there any way we can remove the upper bounds altogether to reduce maintenance burden? Big gems like devise also did this, as did paper_trail, however a bit more conservatively, using a warning.
https://github.com/heartcombo/devise/commit/54fb58226976984bf7b322a2136d25921093fa85
https://github.com/paper-trail-gem/paper_trail/commit/a107146dedc6e1af8c5cf226a44c1adc3b223c0a
Edit: https://github.com/WeTransfer/zip_tricks/blob/master/CHANGELOG.md
=> Loosen zip_tricks dependency

zipline.gemspec
Needed for a fix in zip_tricks 5.3, which fixes a bug with rubyzip 2.1 and above.
Allows rubyzip >= 2 to be used.
I hope this change is okay, since it assumes `zipline` will keep working for all `zip_tricks` releases until 6, but it should reduce the noise of my PRs here. Also, since it seems I keep coming back to this gem for updates, at least there's a high chance I'll open PRs if it should stop working :D.
Anyway, since [I asked for a new release](https://github.com/fringd/zipline/pull/55#issuecomment-627254673) a new release of `zip_tricks` with [this fix](https://github.com/WeTransfer/zip_tricks/pull/67) was released. Which I cannot use with `zipline` until we loosen the dependency again.
=> Loosen zip_tricks dependency (again)

Gemfile, Rakefile, spec/spec_helper.rb
Literally dozens fewer dependencies during development.
Hint was taken from `fog`s post-install message:
```
Post-install message from fog:
------------------------------
Thank you for installing fog!
IMPORTANT NOTICE:
If there's a metagem available for your cloud provider, e.g. `fog-aws`,
you should be using it instead of requiring the full fog collection to avoid
unnecessary dependencies.
'fog' should be required explicitly only if the provider you use doesn't yet
have a metagem available.
------------------------------
```
=> Fewer gems in development

lib/zipline/zip_generator.rb
to improve performance by decreasing the number of syscalls performed by the webserver. See https://github.com/WeTransfer/zip_tricks/issues/78 for the discussion related to this issue. This is likely to improve performance
=> Add output buffering

lib/zipline/zip_generator.rb, spec/lib/zipline/zip_generator_spec.rb
`ActiveStorage::Blob#filename` actually returns an `ActiveStorage::Filename` object since Rails >= 5.2 (added [here](https://github.com/rails/rails/commit/9330d01ada9ce6768d14c59b99cd3860e209737a#diff-5d98a8ec8926dad66a1c94a7c8a15a26794b3c60a0603f4d057ec51da0be9bbd)). Thus, when following the suggestions from the Readme
```ruby
users = User.all
files = users.map { |user| [user.avatar, user.avatar.filename] }
zipline(files, 'avatars.zip')
```
then `user.avatar.filename` is such `ActiveStorage::Filename`. Passing this object further down the line to `zip_tricks` an error is raised here:
https://github.com/WeTransfer/zip_tricks/blob/5b871c0a4321bfcd443d23bdfbb081f30c6d3a96/lib/zip_tricks/streamer.rb#L516
```ruby
def remove_backslash(filename)
filename.tr('\\', '_')
end
```
we can call …
=> support passing an ActiveStorage::Filename object as filename (Rails >= 5.2)

.gitignore, .travis.yml
* Updates CI to run against Ruby 3.0
* Updates CI to not run against Ruby 2.3 anymore (EOL since quite a while already, 2.4 was released in 2016 and is EOL as well already)
I've also git-ignored `.ruby-version`, since I wanted that file to run the tests locally against different Ruby versions.
Ruby 3.0: `16 examples, 0 failures` ✅   🚀
=> Update CI: drop Ruby 2.3, add Ruby 3.0

zipline.gemspec
Thanks for the gem!
After reading issue https://github.com/fringd/zipline/issues/68 (add support for Rails 6.1), I've browsed through the code, and I think we don't even need the entire Rails gem here, but only [actionpack](https://github.com/rails/rails/tree/master/actionpack) to handle the request/response that this gem aims to hook into.
Since there haven't been any changes to ActionPack that should break anything of this gem (I think! :D), we can relax requirements to `< 7.0`.
I've sorted the dependencies in alphabetical order (default rubocop suggestion) --feel free to sort this back if you mind.
closes https://github.com/fringd/zipline/issues/68
=> swap dependency: rails -> actionpack, relax version restriction on actionpack (allowing Rails 6.1)

lib/zipline/zip_generator.rb, spec/lib/zipline/zip_generator_spec.rb
Fixes #75.
The previous implementation took advantage of kwarg/hash interoperability in method calls that was deprecated in Ruby 2.7.2 and dropped in Ruby 3.
=> Fix call to ZipTricks::Streamer#write_deflated_file to match method signature

.github/workflows/ci.yml, lib/zipline.rb, zipline.gemspec
The current method wrongly encodes filenames, the easiest example being a filename containing a space.
Filename: `test 1.zip`
Prior to #81: `test 1.zip`
After #81: `test+1.zip`
After this PR: `test 1.zip`
I've verified locally that the example given in RFC6266 using the euro sign (€) still works.
This is a draft PR, because the [`ActionDispatch::Http::ContentDisposition`](https://github.com/rails/rails/blob/6-0-stable/actionpack/lib/action_dispatch/http/content_disposition.rb) is `:nodoc:` which I believe means private API for Rails.
Additionally, it only exists starting Rails 6.0 while this gem supports Rails (well, `actionpack`) 3.2.1 and above.
https://github.com/fringd/zipline/blob/b5b7d74c16f010f100707358f90158bf911b8ce3/zipline.gemspec#L19
To resolve this, we could raise the minimum …
=> Use `content_disposition` gem for encoding filenames

README.md, lib/zipline.rb, lib/zipline/zip_generator.rb
Allows for options to be passed in (if required).
Sometimes we may need to pass in options in order to access specific functionality. 
In my particular case, I want to pass in the options to allow for duplicate file names to be renamed. The default is `false` but I would like it to be true. Things will still work with the default, as it was before.
```ruby
zipline(@documents.map{ |d| [d.file, d.filename]}, "name.zip", auto_rename_duplicate_filenames: true)
```
Those options are then passed on to the delegated Ziptricks streamer and everyone's happy!
I did not find a test for the zipline helper, so I have simply passed in the parameter and tested it manually on my end. I'm not sure how we would test the `Zipline::zipline` helper method.
Please let me know if there are any issues and I hope …
=> Add: options parameter to zipline

lib/zipline/zip_generator.rb
by @fizvlad
> I'll save some time to anyone trying to find the rails diff which resulted in this
> 
> [`self.response_body = zip_generator` within gem](https://github.com/fringd/zipline/blob/b2ca413656620e217f74f8eed8fef19ffe3f1924/lib/zipline.rb#L21) calls [`response_body=`](https://github.com/rails/rails/blob/v7.1.2/actionpack/lib/action_controller/metal.rb#L209) method within rails, which calls [`body=`](https://github.com/rails/rails/blob/v7.1.2/actionpack/lib/action_dispatch/http/response.rb#L325) on [`Response`](https://github.com/rails/rails/blob/v7.1.2/actionpack/lib/action_dispatch/http/response.rb#L36) object, which results in assigning of [`Buffer`](https://github.com/rails/rails/blob/v7.1.2/actionpack/lib/action_dispatch/http/response.rb#L98) built based of unchanged …
=> fix rails 7 compatibility

lib/zipline/zip_generator.rb, spec/lib/zipline/zipline_spec.rb
It can happen that the serving gets aborted, and in a lot of cases streaming Rack bodies will not relay exceptions into the APM system like Appsignal etc. It can be useful to at least print the message into the log then.
Closes https://github.com/fringd/zipline/issues/74
=> Print into Rails log when streaming fails

zipline.gemspec
The change to the gemspec in 1.6.0 was only allowing 4.x versions of `zip_tricks` to be used. Those were from 2020. There are newer 5.x versions from 2021. This change allows bundler to use the newest `zip_tricks`.
=> allow 5.x versions of zip_tricks to be used

lib/zipline.rb, lib/zipline/zip_handler.rb, spec/lib/zipline/zip_handler_spec.rb, spec/lib/zipline/zipline_spec.rb, zipline.gemspec
Move more work into ZipKit, since it already handles the streaming body and the headers. What is important here is that we handle the `files` correctly - which is what the new ZipHandler will do, inside of the streaming ZipKit body. This reduces the number of interacting classes and objects and the number of conditionals.
ZipKit, in turn, will now not apply the `chunked` transfer encoding unless explicitly asked to. This is a follow-through on https://github.com/julik/zip_kit/issues/2 because using ZipKit with an HTTP/2 webserver requires the transfer encoding to be disabled - HTTP/2 framing will be used instead. Following the suggestions from Samuel I have removed the chunking, but it is still possible to force it. Logging streaming exceptions is also easier now, as the entire block …
=> Replace ZipGenerator with ZipHandler
